<?php
function cbn_module_block_info() {
    $blocks = array();
    $blocks['cbn_modules'] = array(
       'info' => t("CBN Module: Ajustes varios web site CBN"),
       'cache' => DRUPAL_CACHE_CUSTOM,
        );
    return $blocks;
}

function cbn_module_form_alter(&$form, $form_state, $form_id) {
  
  if($form_id == 'views-exposed-form-recetario-page' && $form_state['view']->name == 'recetario') {
    $form['type']['#options']['all'] = t('aqui vaaaa');
  }
}