<?php
function cbn_module_block_info() {
    $blocks = array();
    $blocks['cbn_modules'] = array(
       'info' => t("CBN Module: Ajustes varios web site CBN"),
       'cache' => DRUPAL_CACHE_CUSTOM,
        );
    return $blocks;
}

function cbn_module_form_alter(&$form, $form_state, $form_id) {

  var_dump("var_dump");
  var_dump($form);
  var_dump("-------------------");
  var_dump($form_state);
  var_dump("-------------------");
  var_dump($form_id);
  
  if($form_id == 'views-exposed-form' && $form_state['view']->name == 'recetario'
    && $form['#id'] == 'views-exposed-form-recetario-page') {
    $form['type']['#options']['all'] = t('Aqui va');
  }
}
