<?php
/**
 * @file
 * Módulo de revisión para palabras prohibidas en las contraseñas
 */


function blaklist_password_block_info() {
    $blocks = array();
    $blocks['blaklist_password'] = array(
       'info' => t("Lista de palabras bloqueadas para la creación de contraseñas"),
       'cache' => DRUPAL_CACHE_CUSTOM,
        );
    return $blocks;
}

// Alter the registration form
function blaklist_password_form_user_register_alter(&$form, &$form_state) {
  // Add your own function to the array of validation callbacks
  $form['#validate'][] = 'blaklist_password_user_register_validate';
}