<?php
/**
 * @file
 * Módulo de revisión para palabras prohibidas en las contraseñas
 */


function blaklist_password_block_info() {
    $blocks = array();
    $blocks['blaklist_password'] = array(
       'info' => t("Lista de palabras bloqueadas para la creación de contraseñas"),
       'cache' => DRUPAL_CACHE_CUSTOM,
        );
    return $blocks;
}

// Alter the registration form

function busquedaPalabra(){
	$result = db_select('blacklist_password','palabras')
   		 ->fields('palabras')
    	 ->condition('activa','S','=')
         ->execute();

    	while($record = $result->fetchAssoc()) {
        $palabra[]=$record['palabra'];
   		 }
		return $palabra;
}


function blaklist_password_form_alter(&$form, &$form_state, $form_id) {

	$palabra=array();
	
	if($form_id=='user_register_form'){
		
		$blacklist = busquedaPalabra();
		echo '<pre>';
		print_r(array_keys($form));
		echo '</pre>';
  		//$password = $form_state['values']['comment_body'][LANGUAGE_NONE][0]['value'];
		
	}


	

  
}

/*Para probar
foreach($blacklist as $word) {
    if(strpos($comment, $word) !== FALSE) {
      form_set_error("comment", t("Using word @word is not allowed.", array('@word' => $word));
      break;
    }
  }

*/