<?php
function cbn_hour_momentos_block_info() {
    $blocks = array();
    $blocks['cbn_modules'] = array(
       'info' => t("CBN Module: Ajustes varios web site CBN"),
       'cache' => DRUPAL_CACHE_CUSTOM,
        );
    return $blocks;
}

function cbn_hour_momentos_views_post_execute(&$view) {
$newResults = array();

if($view->name == "recetario_1er_tiempo" && $view->current_display == "block_9"){
  foreach ($view->result as $result) {
    if($h >= 0501 && $h <= 0900){
        var_dump("estamos en el Desayuno");
        if(isset($result->_field_data["nid"]["entity"]->field_momentos["und"] )){
        foreach ($result->_field_data["nid"]["entity"]->field_momentos["und"] as $key => $value) {
              if($value["tid"]=="1157"){
                //var_dump($result->_field_data["nid"]["entity"]);
                //var_dump("entro!!");
                $newResults[]=$result;
              }
          }
        }
      }elseif($h >= 1101 && $h <= 1400){
        var_dump("estamos en el Almuerzo");
        if(isset($result->_field_data["nid"]["entity"]->field_momentos["und"] )){
          foreach ($result->_field_data["nid"]["entity"]->field_momentos["und"] as $key => $value) {
                if($value["tid"]=="1160"){
                  //var_dump($result->_field_data["nid"]["entity"]);
                  //var_dump("entro!!");
                  $newResults[]=$result;
                }
            }
        }
      }
  }
}



$view->result = $newResults;
}
