<?php
function cbn_preferences_user_block_info() {
    $blocks = array();
    $blocks['cbn_modules'] = array(
       'info' => t("CBN Prefences User: Captura las vistas de articulos y los filtra por la preferencia de los usuarios"),
       'cache' => DRUPAL_CACHE_CUSTOM,
        );
    return $blocks;
}


function cbn_preferences_user_views_post_execute(&$view) {
	$newResults = array();	
	if ($view->name == 'view_bienestar_articulos' && $view->current_display == 'block') {

		$preferences = array("1","2","3","4","5","6");

		var_dump($view->name);
		var_dump("*********");
		var_dump($view->current_display);
	    global $user; 	    
	    foreach ($view->result as &$result) {
	        var_dump($result);
	        var_dump("-------------------------------------");
	    }
	}
	$view->result = $newResults;
}