<?php
function cbn_preferences_user_block_info() {
    $blocks = array();
    $blocks['cbn_modules'] = array(
       'info' => t("CBN Prefences User: Captura las vistas de articulos y los filtra por la preferencia de los usuarios"),
       'cache' => DRUPAL_CACHE_CUSTOM,
        );
    return $blocks;
}


function cbn_preferences_user_views_post_execute(&$view) {
	$newResults = array();	
	if ($view->name == 'view_bienestar_articulos' && $view->current_display == 'block') {

		$preferences = array("1179","2","3","1181","5","1182");

	    global $user;
	    //if($user->uid != 0){ 	    
		    foreach ($view->result as &$result) {

		       // var_dump($result->_field_data["nid"]["entity"]->field_contenido_preferencias);
		        //var_dump("-------------------------------------");

		        if(isset($result->_field_data["nid"]["entity"]->field_contenido_preferencias["und"])){
		        	//var_dump("entro al UND");
		        	foreach ($result->_field_data["nid"]["entity"]->field_contenido_preferencias["und"] as $value) {
		        		//var_dump($value["tid"]);
		        		foreach ($preferences as $valuePrefe) {
		        			//var_dump($valuePrefe);
		        			if($value["tid"] == $valuePrefe){
		        				//var_dump($valuePrefe);
		        				$newResults[]=$result;
		        			}
		        		}
		        	}
		        }
		    }
		//}
	}
	if(count($newResults) >= 3){
		//var_dump("envio");
	 $view->result = $newResults;
	}
}